### ISSUE TITLE
Error when closing the application in Windows 10

### ISSUE THREAD

**Issue by sayonara-sama** [treble-snake/magic-investool#19]
![image](https://user-images.githubusercontent.com/2082734/154441140-7c8d0309-cf4b-436a-b2d1-7de1f3161b2c.png)

**Comment by treble-snake** [comment]
Thanks! Apparently, need to add OS checks for `app.dock` operations.

**Comment by treble-snake** [comment]
Fixed in [0.10.1](https://github.com/treble-snake/magic-investool/releases/tag/v0.10.1)
